//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLanguage {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppLanguage.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string BtnNewAdd {
            get {
                return ResourceManager.GetString("BtnNewAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取账号 的本地化字符串。
        /// </summary>
        public static string BtnPickupAccount {
            get {
                return ResourceManager.GetString("BtnPickupAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string BtnQuery {
            get {
                return ResourceManager.GetString("BtnQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表 的本地化字符串。
        /// </summary>
        public static string BtnReport {
            get {
                return ResourceManager.GetString("BtnReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 举报 的本地化字符串。
        /// </summary>
        public static string BtnReporting {
            get {
                return ResourceManager.GetString("BtnReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string BtnUpdate {
            get {
                return ResourceManager.GetString("BtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户分类归档 的本地化字符串。
        /// </summary>
        public static string LblAccountGroup {
            get {
                return ResourceManager.GetString("LblAccountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 追加显示 的本地化字符串。
        /// </summary>
        public static string LblAppendDisplay {
            get {
                return ResourceManager.GetString("LblAppendDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统程序管理 的本地化字符串。
        /// </summary>
        public static string LblAppManage {
            get {
                return ResourceManager.GetString("LblAppManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置 的本地化字符串。
        /// </summary>
        public static string LblAppSetValue {
            get {
                return ResourceManager.GetString("LblAppSetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        public static string LblBeginTime {
            get {
                return ResourceManager.GetString("LblBeginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 助记码 的本地化字符串。
        /// </summary>
        public static string LblCode {
            get {
                return ResourceManager.GetString("LblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述内容 的本地化字符串。
        /// </summary>
        public static string LblDesc {
            get {
                return ResourceManager.GetString("LblDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string LblDescription {
            get {
                return ResourceManager.GetString("LblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示照片 的本地化字符串。
        /// </summary>
        public static string LblDisplayImg {
            get {
                return ResourceManager.GetString("LblDisplayImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间 的本地化字符串。
        /// </summary>
        public static string LblEndTime {
            get {
                return ResourceManager.GetString("LblEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        public static string LblFullName {
            get {
                return ResourceManager.GetString("LblFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        public static string LblGender {
            get {
                return ResourceManager.GetString("LblGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 归类 的本地化字符串。
        /// </summary>
        public static string LblGroup {
            get {
                return ResourceManager.GetString("LblGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键词 的本地化字符串。
        /// </summary>
        public static string LblKeyWord {
            get {
                return ResourceManager.GetString("LblKeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string LblName {
            get {
                return ResourceManager.GetString("LblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增菜单 的本地化字符串。
        /// </summary>
        public static string LblNewMenu {
            get {
                return ResourceManager.GetString("LblNewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父节点 的本地化字符串。
        /// </summary>
        public static string LblParentCode {
            get {
                return ResourceManager.GetString("LblParentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集时间 的本地化字符串。
        /// </summary>
        public static string LblPickUpTime {
            get {
                return ResourceManager.GetString("LblPickUpTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 均价 的本地化字符串。
        /// </summary>
        public static string LblPrice {
            get {
                return ResourceManager.GetString("LblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参考图 的本地化字符串。
        /// </summary>
        public static string LblReferencePicture {
            get {
                return ResourceManager.GetString("LblReferencePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 举报分类 的本地化字符串。
        /// </summary>
        public static string LblReportingType {
            get {
                return ResourceManager.GetString("LblReportingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string LblSelectAll {
            get {
                return ResourceManager.GetString("LblSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送邮件 的本地化字符串。
        /// </summary>
        public static string LblSendEmail {
            get {
                return ResourceManager.GetString("LblSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生僻字拼音维护 的本地化字符串。
        /// </summary>
        public static string LblSpecialSpellNameManage {
            get {
                return ResourceManager.GetString("LblSpecialSpellNameManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存管理 的本地化字符串。
        /// </summary>
        public static string LblStockManage {
            get {
                return ResourceManager.GetString("LblStockManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存数量 的本地化字符串。
        /// </summary>
        public static string LblStockNumber {
            get {
                return ResourceManager.GetString("LblStockNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string LblTip {
            get {
                return ResourceManager.GetString("LblTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ号 的本地化字符串。
        /// </summary>
        public static string LblUinAccount {
            get {
                return ResourceManager.GetString("LblUinAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 qq图片分类汇总处理 的本地化字符串。
        /// </summary>
        public static string LblUinImgGroupManage {
            get {
                return ResourceManager.GetString("LblUinImgGroupManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网址 的本地化字符串。
        /// </summary>
        public static string LblUrl {
            get {
                return ResourceManager.GetString("LblUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string LblUserName {
            get {
                return ResourceManager.GetString("LblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出发地 的本地化字符串。
        /// </summary>
        public static string Tip_12306_GoStation {
            get {
                return ResourceManager.GetString("Tip_12306_GoStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询车票时，必须提供的信息有：【{0}】,当前未输入项有:【{1}】 的本地化字符串。
        /// </summary>
        public static string Tip_12306_QueryTicketIsRequired {
            get {
                return ResourceManager.GetString("Tip_12306_QueryTicketIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目的地 的本地化字符串。
        /// </summary>
        public static string Tip_12306_ToStation {
            get {
                return ResourceManager.GetString("Tip_12306_ToStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码【{0}】已被使用 的本地化字符串。
        /// </summary>
        public static string Tip_CodeHasUsed {
            get {
                return ResourceManager.GetString("Tip_CodeHasUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单路径不能为空。 的本地化字符串。
        /// </summary>
        public static string Tip_MenuUrlIsRequired {
            get {
                return ResourceManager.GetString("Tip_MenuUrlIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        public static string Tip_PleaseSelect {
            get {
                return ResourceManager.GetString("Tip_PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择数据 的本地化字符串。
        /// </summary>
        public static string Tip_PleaseSelectData {
            get {
                return ResourceManager.GetString("Tip_PleaseSelectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择文件 的本地化字符串。
        /// </summary>
        public static string Tip_PleaseSelectFile {
            get {
                return ResourceManager.GetString("Tip_PleaseSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择父节点 的本地化字符串。
        /// </summary>
        public static string Tip_PleaseSelectParentNode {
            get {
                return ResourceManager.GetString("Tip_PleaseSelectParentNode", resourceCulture);
            }
        }
    }
}
